### ISSUE TITLE
Please add documentation to every script

### ISSUE THREAD

**Issue by vitaly-zdanevich** [DanielFGray/bin#1]
And maybe every script should be on it own repo? To have a clear git history, and logical separation of unrelated stuff.

**Comment by DanielFGray** [comment]
No

**Comment by vitaly-zdanevich** [comment]
But just for me please - what is this script about? https://github.com/DanielFGray/bin/blob/master/v

**Comment by DanielFGray** [comment]
Basically

* Start a nested tmux session if one isn't found
* Start a [n]vim server if one isn't found
* Open files or send arguments to [n]vim

It could definitely use some refactoring
